---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: {{buildpacks-docker-ci-repo}}
inputs:
  - name: buildpacks-ci
  - name: brats
  - name: cf-environments
run:
  path: buildpacks-ci/scripts/brats
