---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: orangeopensource/cfbuildpacks-ci
inputs:
  - name: buildpacks-ci
params:
  TERM: xterm-color
  CI_USERNAME:
  CI_PASSWORD:
run:
  path: bash
  args:
    - "-c"
    - |
      set -ex
      cd buildpacks-ci
      ./scripts/fly-login $CI_USERNAME $CI_PASSWORD
      bundle
      rspec --format documentation
      ./scripts/set-status-success
