---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: {{buildpacks-docker-ci-repo}}
inputs:
  - name: buildpacks-ci
  - name: buildpack-checksums
  - name: buildpack-artifacts
outputs:
  - name: sha-artifacts
run:
  path: buildpacks-ci/scripts/release/commit-shas
