platform: linux
image_resource:
  type: docker-image
  source:
    repository: {{buildpacks-docker-ci-repo}}
inputs:
  - name: blob
outputs:
  - name: version
run:
  path: bash
  args:
    - -c
    - cp blob/version version/number
