---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: {{buildpacks-docker-ci-repo}}
inputs:
  - name: buildpacks-ci
  - name: buildpack
  - name: pivotal-buildpacks-cached
outputs:
  - name: buildpack-artifacts
run:
  path: bash
  args:
    - -cl
    - buildpacks-ci/scripts/release/finalize-buildpack
