---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: {{buildpacks-docker-ci-repo}}
inputs:
  - name: buildpacks-ci
  - name: stacks
  - name: version
  - name: stacks-artifacts
run:
  path: buildpacks-ci/scripts/stacks/test-rootfs
