---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: {{buildpacks-docker-ci-repo}}
inputs:
  - name: buildpacks-ci
  - name: buildpacks-pivnet-uploader
  - name: pivotal-buildpacks-cached
  - name: buildpack-artifacts
  - name: buildpack
run:
  path: buildpacks-ci/scripts/release/upload_to_pivnet
