
resources:
  - name: buildpacks-ci
    type: git
    source:
      uri: {{buildpacks-ci-git-uri-public}}
      branch:  {{buildpacks-ci-git-uri-public-branch}}
      paths: [ "lib/concourse2tracker-resource" ]
  - name: concourse2tracker-image
    type: docker-image
    source:
      repository: {{buildpacks-docker-repo}}
      email: {{buildpacks-email}}
      username: {{buildpacks-docker-username}}
      password: {{buildpacks-docker-password}}

jobs:
  - name: concourse2tracker-build
    serial: true
    plan:
      - get: buildpacks-ci
        trigger: true
      - task: rspec
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: {{buildpacks-docker-ci-repo}}
          inputs:
            - name: buildpacks-ci
          run:
            path: bash
            args:
              - -c
              - |
                cd buildpacks-ci/lib/concourse2tracker-resource
                bundle
                bundle exec rspec
      - put: concourse2tracker-image
        params:
          build: buildpacks-ci/lib/concourse2tracker-resource
          push: true
